name: Create Release Assets
on:
  release:
    types: [published]
permissions: 
  contents: write

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup | Checkout repository at workflow sha
        uses: actions/checkout@v4
        with:
          lfs: true
      - run: |
          tar czf dtocean-data-${{ github.event.release.tag_name }}.tar.gz share
          7z a -tzip dtocean-data-${{ github.event.release.tag_name }}.zip share
          gh release upload ${{github.event.release.tag_name}} dtocean-data-${{ github.event.release.tag_name }}.tar.gz
          gh release upload ${{github.event.release.tag_name}} dtocean-data-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
